### ISSUE TITLE
Publisher flow with confirmation

### ISSUE THREAD

**Issue by meln1k** [zalando/reactive-nakadi#11]
It's good to have something like `Flow[ProducerMessage, Seq[String], NotUsed]` where we can receive ids of committed events (and store them somewhere else).

**Comment by dr4ke616** [comment]
So, first off, thanks for the PR. Ive some thoughts though id be interested to discuss. 

First, why just have the `Flow` return only the `event_id` of the `metadata`. In my opinion I think this kind of behaviour is more application specific. The user of this gets a stream of events, its down to the user to actually pull out what they want.

However, I can see why you may have it too. There is an event type in Nakadi called the `DataChangedEvent`, which is an enveloped structure containing the metadata, payload, etc. However there are other event types in Nakadi that do not enforce this structure, such as the `WildCardEvent` (or something like that). It is my understanding that it would be down to the JSON schema defined to enforce extra properties (one such as metadata). This in my opinion causes confusion and inconsistency across the different event types that exist within Nakadi. There for I feel if moving this sort of event level logic to this library may make it tricker to maintain in the future.
